### ISSUE TITLE
pyperclip not in installed_requires

### ISSUE THREAD

**Issue by cltrudeau** [jima80525/markplates#71]
Hi Jim,

I'm playing around with markplates and first run gave me "No module named 'pyperclip'". Easy enough to pip install it, but you probably want to add it to setup.py
...ct

**Comment by jima80525** [comment]
Thanks for the heads up!  I probably won't get to it this week as we're visiting the in-laws, but I'll definitely get that fixed.  I hope you find some usefulness in the tool!
